import{loadSpots,saveSpots}from'./storage.js';
const C=['ご飯','外出'],S=['気になる','今度行く','行った','また行きたい'],P=['高','中','低'],B=['無料','〜1,000円','1,000〜3,000円','3,000〜5,000円','5,000円以上'],G={ご飯:['カフェ','ランチ','ディナー','スイーツ','和食','洋食','イタリアン','フレンチ','中華','韓国料理','居酒屋','バー','ベーカリー','その他'],外出:['美術館','展覧会','映画','芸術','レジャー','体験','ショッピング','街歩き','自然','季節イベント','旅行','ホテル','公園','その他']},O={今度行く:0,気になる:1,また行きたい:2,行った:3},V=new Set(['行った','また行きたい']);
const $=s=>document.querySelector(s),E={grid:$('#spotGrid'),template:$('#spotCardTemplate'),empty:$('#emptyState'),dialog:$('#spotDialog'),form:$('#spotForm'),search:$('#searchInput'),area:$('#areaFilter'),genre:$('#genreFilter'),budget:$('#budgetFilter'),status:$('#statusFilter'),tabs:$('#categoryTabs'),count:$('#resultCount'),heading:$('#resultHeading'),toast:$('#toast')};let spots=loadSpots(),active='すべて',timer;
const opts=(a,p='')=>(p?`<option value="">${p}</option>`:'')+a.map(x=>`<option>${x}</option>`).join('');
function init(){E.form.elements.category.innerHTML=opts(C);E.form.elements.status.innerHTML=opts(S);E.form.elements.priority.innerHTML=opts(P,'選択なし');E.form.elements.budget.innerHTML=opts(B,'選択なし');E.budget.innerHTML=opts(B,'すべて');E.status.innerHTML=opts(S,'すべて');formGenre()}
function formGenre(selected=''){let c=E.form.elements.category.value||'ご飯';E.form.elements.genre.innerHTML=opts(G[c],'選択なし');E.form.elements.genre.value=G[c].includes(selected)?selected:''}
function filterOpts(){let a=[...new Set(spots.map(x=>x.area).filter(Boolean))].sort(),v=E.area.value;E.area.innerHTML=opts(a,'すべて');E.area.value=a.includes(v)?v:'';$('#genreFilterLabel').hidden=active==='すべて';let g=active==='すべて'?[]:G[active],q=E.genre.value;E.genre.innerHTML=opts(g,'すべて');E.genre.value=g.includes(q)?q:''}
function save(next=spots){spots=next;saveSpots(spots);render()}
function filtered(){let q=E.search.value.trim().toLowerCase();return spots.filter(x=>active==='すべて'||x.category===active).filter(x=>!E.area.value||x.area===E.area.value).filter(x=>!E.genre.value||x.genre===E.genre.value).filter(x=>!E.budget.value||x.budget===E.budget.value).filter(x=>!E.status.value||x.status===E.status.value).filter(x=>!q||['name','description','memo','area','genre'].some(k=>(x[k]||'').toLowerCase().includes(q))).sort((a,b)=>O[a.status]-O[b.status]||new Date(b.updatedAt)-new Date(a.updatedAt))}
const date=x=>x?new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'short',day:'numeric'}).format(new Date(x+'T00:00:00')):'';
function card(x){let c=E.template.content.firstElementChild.cloneNode(true),img=c.querySelector('.spot-card__image'),ph=c.querySelector('.spot-card__placeholder');if(x.imageUrl){img.src=x.imageUrl;img.alt=x.name;ph.hidden=true;img.onerror=()=>{img.hidden=true;ph.hidden=false}}else img.hidden=true;c.querySelector('.category-badge').textContent=x.category;let p=c.querySelector('.priority-badge');p.textContent=x.priority?`優先度 ${x.priority}`:'';p.hidden=!x.priority;c.querySelector('h3').textContent=x.name;c.querySelector('.spot-card__meta').textContent=[x.area,x.genre].filter(Boolean).join(' · ')||'場所をあとで決める';let l=c.querySelector('.external-link');l.href=x.url||'#';l.hidden=!x.url;c.querySelector('.spot-card__description').textContent=x.description||'説明はまだありません。';let chips=c.querySelector('.detail-chips');[x.budget,x.status].filter(Boolean).forEach(t=>{let s=document.createElement('span');s.textContent=t;chips.append(s)});let d=c.querySelector('.date-list');if(x.plannedDate)d.insertAdjacentHTML('beforeend',`<div><dt>訪問予定</dt><dd>${date(x.plannedDate)}</dd></div>`);if(x.visitedDate)d.insertAdjacentHTML('beforeend',`<div><dt>訪問日</dt><dd>${date(x.visitedDate)}</dd></div>`);d.hidden=!x.plannedDate&&!x.visitedDate;let m=c.querySelector('.spot-card__memo');m.textContent=x.memo?`メモ：${x.memo}`:'';m.hidden=!x.memo;let st=c.querySelector('.card-status-select'),qv=c.querySelector('.quick-visit-form');st.innerHTML=opts(S);st.value=x.status;qv.hidden=!V.has(x.status);qv.elements.visitedDate.value=x.visitedDate||'';qv.elements.visitLog.value=x.visitLog||'';st.onchange=()=>{if(V.has(st.value)){qv.hidden=false;qv.elements.visitedDate.value||=new Date().toISOString().slice(0,10)}else{save(spots.map(i=>i.id===x.id?{...i,status:st.value,updatedAt:new Date().toISOString()}:i));toast('進捗を更新しました')}};qv.onsubmit=e=>{e.preventDefault();save(spots.map(i=>i.id===x.id?{...i,status:st.value,visitedDate:qv.elements.visitedDate.value,visitLog:qv.elements.visitLog.value,updatedAt:new Date().toISOString()}:i));toast('訪問記録を保存しました')};c.querySelector('.edit-button').onclick=()=>open(x);c.querySelector('.delete-button').onclick=()=>{if(confirm(`「${x.name}」を削除しますか？`)){save(spots.filter(i=>i.id!==x.id));toast('削除しました')}};return c}
function render(){filterOpts();let f=filtered();E.grid.replaceChildren(...f.map(card));E.empty.hidden=f.length>0;E.grid.hidden=f.length===0;$('#emptyTitle').textContent=spots.length?'条件に合うスポットがありません':'まだスポットがありません';E.count.textContent=`${f.length}件 / 全${spots.length}件`;E.heading.textContent=active==='すべて'?'すべてのスポット':`${active}のスポット`}
function visitFields(){E.form.querySelectorAll('.visit-field').forEach(x=>x.hidden=!V.has(E.form.elements.status.value))}
function open(x=null){E.form.reset();$('#formKicker').textContent=x?'EDIT SPOT':'NEW SPOT';$('#formTitle').textContent=x?'スポットを編集':'新しいスポットを追加';E.form.elements.category.value=x?.category||(active==='すべて'?'ご飯':active);formGenre(x?.genre);if(x)Object.entries(x).forEach(([k,v])=>{if(E.form.elements[k])E.form.elements[k].value=v||''});else E.form.elements.status.value='気になる';visitFields();E.dialog.showModal()}
function toast(t){clearTimeout(timer);E.toast.textContent=t;E.toast.classList.add('is-visible');timer=setTimeout(()=>E.toast.classList.remove('is-visible'),2200)}
document.querySelectorAll('#openCreateButton,#emptyCreateButton').forEach(b=>b.onclick=()=>open());document.querySelectorAll('#closeDialogButton,#cancelFormButton').forEach(b=>b.onclick=()=>E.dialog.close());E.form.elements.category.onchange=()=>formGenre();E.form.elements.status.onchange=visitFields;E.form.onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(E.form)),old=spots.find(x=>x.id===d.id),now=new Date().toISOString(),x={...d,id:old?.id||crypto.randomUUID(),createdAt:old?.createdAt||now,updatedAt:now};save(old?spots.map(i=>i.id===x.id?x:i):[x,...spots]);E.dialog.close();toast(old?'更新しました':'追加しました')};E.tabs.onclick=e=>{let t=e.target.closest('[data-category]');if(!t)return;active=t.dataset.category;E.tabs.querySelectorAll('.tab').forEach(x=>x.classList.toggle('is-active',x===t));E.genre.value='';render()};[E.search,E.area,E.genre,E.budget,E.status].forEach(x=>x.addEventListener(x===E.search?'input':'change',render));$('#resetFiltersButton').onclick=()=>{E.search.value='';[E.area,E.genre,E.budget,E.status].forEach(x=>x.value='');render()};init();render();
